name: isdf
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - conda-package-handling
  - cryptography
  - idna
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libspatialindex
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip=21.2.4
  - pycosat
  - pycparser
  - pyopenssl
  - pysocks
  - python=3.8.5
  - readline
  - requests
  - ruamel_yaml
  - six
  - sqlite
  - tk
  - tqdm
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - pip:
    - absl-py
    - addict
    - anyio
    - argon2-cffi
    - attrs
    - autoprop
    - babel
    - backcall
    - beautifulsoup4
    - bleach
    - cachetools
    - catkin-pkg
    - click
    - colorlog
    - colour
    - cycler
    - cython
    - debugpy
    - decorator
    - defusedxml
    - deprecation
    - distro
    - docutils
    - entrypoints
    - fastjsonschema
    - filelock
    - freetype-py
    - future
    - gdown
    - gitdb
    - gitpython
    - glooey
    - google-auth
    - google-auth-oauthlib
    - gputil
    - grpcio
    - h5py
    - imageio
    - imageio-ffmpeg
    - imgviz
    - importlib-metadata
    - ipdb
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - joblib
    - json5
    - jsonpatch
    - jsonpointer
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyter-packaging
    - jupyter-server
    - jupyterlab
    - jupyterlab-pygments
    - jupyterlab-server
    - jupyterlab-widgets
    - kiwisolver
    - llvmlite
    - lxml
    - markdown
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mesh-to-sdf
    - mistune
    - more-itertools
    - mpmath
    - msgpack
    - nbclassic
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - netifaces
    - networkx
    - notebook
    - notebook-shim
    - numba
    - numpy
    - oauthlib
    - open3d
    - opencv-python
    - ordered-set
    - packaging
    - pandas
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - pika
    - pillow
    - plotly
    - plyfile
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - ptyprocess
    - py-vox-io
    - pyasn1
    - pyasn1-modules
    - pycollada
    - pydot
    - pyglet==1.5.19
    - pygments
    - pyhocon
    - pyopengl
    - pyparsing
    - pyrender
    - pyrsistent
    - python-dateutil
    - pytz
    - pywavelets
    - pyyaml
    - pyzmq
    - requests-oauthlib
    - rospkg
    - rsa
    - rtree
    - scikit-image
    - scikit-learn
    - scipy
    - send2trash
    - setuptools==63.2.0
    - shapely
    - signature-dispatch
    - sklearn
    - smmap
    - sniffio
    - soupsieve
    - svg-path
    - sympy
    - tenacity
    - terminado
    - testpath
    - threadpoolctl
    - tifffile
    - tinycss2
    - toml
    - tomlkit
    - tornado
    - traitlets
    - trimesh
    - typeguard
    - typing-extensions
    - urdfpy
    - vecrec
    - video-cli
    - visdom
    - wcwidth
    - webencodings
    - websocket-client
    - werkzeug
    - widgetsnbextension
    - xxhash
    - zipp


